// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/battery_manager.proto

package cuteboot.grpcbridge;

public final class BatteryManagerProtos {
  private BatteryManagerProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EmptyRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:grpcbridge.EmptyRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code grpcbridge.EmptyRequest}
   */
  public  static final class EmptyRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:grpcbridge.EmptyRequest)
      EmptyRequestOrBuilder {
    // Use EmptyRequest.newBuilder() to construct.
    private EmptyRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private EmptyRequest() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private EmptyRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cuteboot.grpcbridge.BatteryManagerProtos.internal_static_grpcbridge_EmptyRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cuteboot.grpcbridge.BatteryManagerProtos.internal_static_grpcbridge_EmptyRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cuteboot.grpcbridge.BatteryManagerProtos.EmptyRequest.class, cuteboot.grpcbridge.BatteryManagerProtos.EmptyRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static cuteboot.grpcbridge.BatteryManagerProtos.EmptyRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cuteboot.grpcbridge.BatteryManagerProtos.EmptyRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cuteboot.grpcbridge.BatteryManagerProtos.EmptyRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cuteboot.grpcbridge.BatteryManagerProtos.EmptyRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cuteboot.grpcbridge.BatteryManagerProtos.EmptyRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
    public static cuteboot.grpcbridge.BatteryManagerProtos.EmptyRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}
    public static cuteboot.grpcbridge.BatteryManagerProtos.EmptyRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);}
    public static cuteboot.grpcbridge.BatteryManagerProtos.EmptyRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);}
    public static cuteboot.grpcbridge.BatteryManagerProtos.EmptyRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
    public static cuteboot.grpcbridge.BatteryManagerProtos.EmptyRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cuteboot.grpcbridge.BatteryManagerProtos.EmptyRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code grpcbridge.EmptyRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:grpcbridge.EmptyRequest)
        cuteboot.grpcbridge.BatteryManagerProtos.EmptyRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cuteboot.grpcbridge.BatteryManagerProtos.internal_static_grpcbridge_EmptyRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cuteboot.grpcbridge.BatteryManagerProtos.internal_static_grpcbridge_EmptyRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cuteboot.grpcbridge.BatteryManagerProtos.EmptyRequest.class, cuteboot.grpcbridge.BatteryManagerProtos.EmptyRequest.Builder.class);
      }

      // Construct using cuteboot.grpcbridge.BatteryManagerProtos.EmptyRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cuteboot.grpcbridge.BatteryManagerProtos.internal_static_grpcbridge_EmptyRequest_descriptor;
      }

      public cuteboot.grpcbridge.BatteryManagerProtos.EmptyRequest getDefaultInstanceForType() {
        return cuteboot.grpcbridge.BatteryManagerProtos.EmptyRequest.getDefaultInstance();
      }

      public cuteboot.grpcbridge.BatteryManagerProtos.EmptyRequest build() {
        cuteboot.grpcbridge.BatteryManagerProtos.EmptyRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cuteboot.grpcbridge.BatteryManagerProtos.EmptyRequest buildPartial() {
        cuteboot.grpcbridge.BatteryManagerProtos.EmptyRequest result = new cuteboot.grpcbridge.BatteryManagerProtos.EmptyRequest(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cuteboot.grpcbridge.BatteryManagerProtos.EmptyRequest) {
          return mergeFrom((cuteboot.grpcbridge.BatteryManagerProtos.EmptyRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cuteboot.grpcbridge.BatteryManagerProtos.EmptyRequest other) {
        if (other == cuteboot.grpcbridge.BatteryManagerProtos.EmptyRequest.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cuteboot.grpcbridge.BatteryManagerProtos.EmptyRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cuteboot.grpcbridge.BatteryManagerProtos.EmptyRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:grpcbridge.EmptyRequest)
    }

    // @@protoc_insertion_point(class_scope:grpcbridge.EmptyRequest)
    private static final cuteboot.grpcbridge.BatteryManagerProtos.EmptyRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cuteboot.grpcbridge.BatteryManagerProtos.EmptyRequest();
    }

    public static cuteboot.grpcbridge.BatteryManagerProtos.EmptyRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EmptyRequest>
        PARSER = new com.google.protobuf.AbstractParser<EmptyRequest>() {
      public EmptyRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new EmptyRequest(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<EmptyRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EmptyRequest> getParserForType() {
      return PARSER;
    }

    public cuteboot.grpcbridge.BatteryManagerProtos.EmptyRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BooleanResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:grpcbridge.BooleanResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool value = 1;</code>
     */
    boolean getValue();
  }
  /**
   * Protobuf type {@code grpcbridge.BooleanResponse}
   */
  public  static final class BooleanResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:grpcbridge.BooleanResponse)
      BooleanResponseOrBuilder {
    // Use BooleanResponse.newBuilder() to construct.
    private BooleanResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private BooleanResponse() {
      value_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private BooleanResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              value_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cuteboot.grpcbridge.BatteryManagerProtos.internal_static_grpcbridge_BooleanResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cuteboot.grpcbridge.BatteryManagerProtos.internal_static_grpcbridge_BooleanResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cuteboot.grpcbridge.BatteryManagerProtos.BooleanResponse.class, cuteboot.grpcbridge.BatteryManagerProtos.BooleanResponse.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private boolean value_;
    /**
     * <code>optional bool value = 1;</code>
     */
    public boolean getValue() {
      return value_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (value_ != false) {
        output.writeBool(1, value_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (value_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, value_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static cuteboot.grpcbridge.BatteryManagerProtos.BooleanResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cuteboot.grpcbridge.BatteryManagerProtos.BooleanResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cuteboot.grpcbridge.BatteryManagerProtos.BooleanResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cuteboot.grpcbridge.BatteryManagerProtos.BooleanResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cuteboot.grpcbridge.BatteryManagerProtos.BooleanResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
    public static cuteboot.grpcbridge.BatteryManagerProtos.BooleanResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}
    public static cuteboot.grpcbridge.BatteryManagerProtos.BooleanResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);}
    public static cuteboot.grpcbridge.BatteryManagerProtos.BooleanResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);}
    public static cuteboot.grpcbridge.BatteryManagerProtos.BooleanResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
    public static cuteboot.grpcbridge.BatteryManagerProtos.BooleanResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cuteboot.grpcbridge.BatteryManagerProtos.BooleanResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code grpcbridge.BooleanResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:grpcbridge.BooleanResponse)
        cuteboot.grpcbridge.BatteryManagerProtos.BooleanResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cuteboot.grpcbridge.BatteryManagerProtos.internal_static_grpcbridge_BooleanResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cuteboot.grpcbridge.BatteryManagerProtos.internal_static_grpcbridge_BooleanResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cuteboot.grpcbridge.BatteryManagerProtos.BooleanResponse.class, cuteboot.grpcbridge.BatteryManagerProtos.BooleanResponse.Builder.class);
      }

      // Construct using cuteboot.grpcbridge.BatteryManagerProtos.BooleanResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        value_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cuteboot.grpcbridge.BatteryManagerProtos.internal_static_grpcbridge_BooleanResponse_descriptor;
      }

      public cuteboot.grpcbridge.BatteryManagerProtos.BooleanResponse getDefaultInstanceForType() {
        return cuteboot.grpcbridge.BatteryManagerProtos.BooleanResponse.getDefaultInstance();
      }

      public cuteboot.grpcbridge.BatteryManagerProtos.BooleanResponse build() {
        cuteboot.grpcbridge.BatteryManagerProtos.BooleanResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cuteboot.grpcbridge.BatteryManagerProtos.BooleanResponse buildPartial() {
        cuteboot.grpcbridge.BatteryManagerProtos.BooleanResponse result = new cuteboot.grpcbridge.BatteryManagerProtos.BooleanResponse(this);
        result.value_ = value_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cuteboot.grpcbridge.BatteryManagerProtos.BooleanResponse) {
          return mergeFrom((cuteboot.grpcbridge.BatteryManagerProtos.BooleanResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cuteboot.grpcbridge.BatteryManagerProtos.BooleanResponse other) {
        if (other == cuteboot.grpcbridge.BatteryManagerProtos.BooleanResponse.getDefaultInstance()) return this;
        if (other.getValue() != false) {
          setValue(other.getValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cuteboot.grpcbridge.BatteryManagerProtos.BooleanResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cuteboot.grpcbridge.BatteryManagerProtos.BooleanResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean value_ ;
      /**
       * <code>optional bool value = 1;</code>
       */
      public boolean getValue() {
        return value_;
      }
      /**
       * <code>optional bool value = 1;</code>
       */
      public Builder setValue(boolean value) {
        
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool value = 1;</code>
       */
      public Builder clearValue() {
        
        value_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:grpcbridge.BooleanResponse)
    }

    // @@protoc_insertion_point(class_scope:grpcbridge.BooleanResponse)
    private static final cuteboot.grpcbridge.BatteryManagerProtos.BooleanResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cuteboot.grpcbridge.BatteryManagerProtos.BooleanResponse();
    }

    public static cuteboot.grpcbridge.BatteryManagerProtos.BooleanResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BooleanResponse>
        PARSER = new com.google.protobuf.AbstractParser<BooleanResponse>() {
      public BooleanResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new BooleanResponse(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<BooleanResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BooleanResponse> getParserForType() {
      return PARSER;
    }

    public cuteboot.grpcbridge.BatteryManagerProtos.BooleanResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetPropertyRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:grpcbridge.GetPropertyRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();
  }
  /**
   * Protobuf type {@code grpcbridge.GetPropertyRequest}
   */
  public  static final class GetPropertyRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:grpcbridge.GetPropertyRequest)
      GetPropertyRequestOrBuilder {
    // Use GetPropertyRequest.newBuilder() to construct.
    private GetPropertyRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GetPropertyRequest() {
      id_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetPropertyRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cuteboot.grpcbridge.BatteryManagerProtos.internal_static_grpcbridge_GetPropertyRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cuteboot.grpcbridge.BatteryManagerProtos.internal_static_grpcbridge_GetPropertyRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyRequest.class, cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyRequest.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
    public static cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}
    public static cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);}
    public static cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);}
    public static cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
    public static cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code grpcbridge.GetPropertyRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:grpcbridge.GetPropertyRequest)
        cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cuteboot.grpcbridge.BatteryManagerProtos.internal_static_grpcbridge_GetPropertyRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cuteboot.grpcbridge.BatteryManagerProtos.internal_static_grpcbridge_GetPropertyRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyRequest.class, cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyRequest.Builder.class);
      }

      // Construct using cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cuteboot.grpcbridge.BatteryManagerProtos.internal_static_grpcbridge_GetPropertyRequest_descriptor;
      }

      public cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyRequest getDefaultInstanceForType() {
        return cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyRequest.getDefaultInstance();
      }

      public cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyRequest build() {
        cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyRequest buildPartial() {
        cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyRequest result = new cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyRequest(this);
        result.id_ = id_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyRequest) {
          return mergeFrom((cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyRequest other) {
        if (other == cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyRequest.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:grpcbridge.GetPropertyRequest)
    }

    // @@protoc_insertion_point(class_scope:grpcbridge.GetPropertyRequest)
    private static final cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyRequest();
    }

    public static cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetPropertyRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetPropertyRequest>() {
      public GetPropertyRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new GetPropertyRequest(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<GetPropertyRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetPropertyRequest> getParserForType() {
      return PARSER;
    }

    public cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetPropertyResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:grpcbridge.GetPropertyResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 value = 1;</code>
     */
    long getValue();
  }
  /**
   * Protobuf type {@code grpcbridge.GetPropertyResponse}
   */
  public  static final class GetPropertyResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:grpcbridge.GetPropertyResponse)
      GetPropertyResponseOrBuilder {
    // Use GetPropertyResponse.newBuilder() to construct.
    private GetPropertyResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GetPropertyResponse() {
      value_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetPropertyResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              value_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cuteboot.grpcbridge.BatteryManagerProtos.internal_static_grpcbridge_GetPropertyResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cuteboot.grpcbridge.BatteryManagerProtos.internal_static_grpcbridge_GetPropertyResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyResponse.class, cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyResponse.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private long value_;
    /**
     * <code>optional int64 value = 1;</code>
     */
    public long getValue() {
      return value_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (value_ != 0L) {
        output.writeInt64(1, value_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (value_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, value_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
    public static cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}
    public static cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);}
    public static cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);}
    public static cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
    public static cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code grpcbridge.GetPropertyResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:grpcbridge.GetPropertyResponse)
        cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cuteboot.grpcbridge.BatteryManagerProtos.internal_static_grpcbridge_GetPropertyResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cuteboot.grpcbridge.BatteryManagerProtos.internal_static_grpcbridge_GetPropertyResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyResponse.class, cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyResponse.Builder.class);
      }

      // Construct using cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        value_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cuteboot.grpcbridge.BatteryManagerProtos.internal_static_grpcbridge_GetPropertyResponse_descriptor;
      }

      public cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyResponse getDefaultInstanceForType() {
        return cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyResponse.getDefaultInstance();
      }

      public cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyResponse build() {
        cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyResponse buildPartial() {
        cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyResponse result = new cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyResponse(this);
        result.value_ = value_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyResponse) {
          return mergeFrom((cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyResponse other) {
        if (other == cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyResponse.getDefaultInstance()) return this;
        if (other.getValue() != 0L) {
          setValue(other.getValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long value_ ;
      /**
       * <code>optional int64 value = 1;</code>
       */
      public long getValue() {
        return value_;
      }
      /**
       * <code>optional int64 value = 1;</code>
       */
      public Builder setValue(long value) {
        
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 value = 1;</code>
       */
      public Builder clearValue() {
        
        value_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:grpcbridge.GetPropertyResponse)
    }

    // @@protoc_insertion_point(class_scope:grpcbridge.GetPropertyResponse)
    private static final cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyResponse();
    }

    public static cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetPropertyResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetPropertyResponse>() {
      public GetPropertyResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new GetPropertyResponse(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<GetPropertyResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetPropertyResponse> getParserForType() {
      return PARSER;
    }

    public cuteboot.grpcbridge.BatteryManagerProtos.GetPropertyResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_grpcbridge_EmptyRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grpcbridge_EmptyRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_grpcbridge_BooleanResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grpcbridge_BooleanResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_grpcbridge_GetPropertyRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grpcbridge_GetPropertyRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_grpcbridge_GetPropertyResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grpcbridge_GetPropertyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034protos/battery_manager.proto\022\ngrpcbrid" +
      "ge\"\016\n\014EmptyRequest\" \n\017BooleanResponse\022\r\n" +
      "\005value\030\001 \001(\010\" \n\022GetPropertyRequest\022\n\n\002id" +
      "\030\001 \001(\005\"$\n\023GetPropertyResponse\022\r\n\005value\030\001" +
      " \001(\0032\251\001\n\016BatteryManager\022P\n\013GetProperty\022\036" +
      ".grpcbridge.GetPropertyRequest\032\037.grpcbri" +
      "dge.GetPropertyResponse\"\000\022E\n\nIsCharging\022" +
      "\030.grpcbridge.EmptyRequest\032\033.grpcbridge.B" +
      "ooleanResponse\"\000B+\n\023cuteboot.grpcbridgeB" +
      "\024BatteryManagerProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_grpcbridge_EmptyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpcbridge_EmptyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_grpcbridge_EmptyRequest_descriptor,
        new java.lang.String[] { });
    internal_static_grpcbridge_BooleanResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpcbridge_BooleanResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_grpcbridge_BooleanResponse_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_grpcbridge_GetPropertyRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_grpcbridge_GetPropertyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_grpcbridge_GetPropertyRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_grpcbridge_GetPropertyResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_grpcbridge_GetPropertyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_grpcbridge_GetPropertyResponse_descriptor,
        new java.lang.String[] { "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
